LabNET105/Controllers/BillController.cs
using DAL;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using DAL.ViewModel;


namespace LabNET105.Controllers
{
    public class BillController : Controller
    {
        LabDbContext _context;

        public BillController()
        {
            _context = new LabDbContext();
        }
        // GET: BillController


        public IActionResult ListBill()
        {
            try
            {
                Guid userId = Guid.Parse(HttpContext.Session.GetString("uid"));
                ICollection<Bill> model = _context.Bills.Where(x => x.AccountId == userId).OrderByDescending(x => x.BuyDate).ToList();

                return View(model);
            }
            catch
            {
                return RedirectToAction("Index", "Access");
            }

          


        }

        public IActionResult HuyBill(int id)
        {
            var lstBillDetail = _context.BillDetails.Where(x=>x.BillId==id).ToList();
            for(int i = 0; i < lstBillDetail.Count; i++)
            {
                if (_context.Products.FirstOrDefault(x => x.Id == lstBillDetail[i].ProductId) != null)
                {
                    var obj = _context.Products.FirstOrDefault(x => x.Id == lstBillDetail[i].ProductId);
                    obj.Quantity += lstBillDetail[i].Quantity;
                    _context.Products.Update(obj);
                    _context.SaveChanges();
                }    
            }
            var statusbill = _context.Bills.Find(id);
            statusbill.Status = 100;
            _context.Bills.Update(statusbill);
            _context.SaveChanges();
            return RedirectToAction("Index", "Product");
            // nef
        }
        // GET: BillController/Details/5
        public ActionResult Details(int id)
        {
            var list = (from billdetail in _context.BillDetails
                        join product in _context.Products on billdetail.ProductId equals product.Id
                        where billdetail.BillId == id
                        select new BillDetailViewModel
                        {
                            BillId = id,
                            ProductId = product.Id,
                            ProductName = product.Name,
                            Quantity = billdetail.Quantity,
                            Price = billdetail.Price,
                            Status = 1,
                            TotalPrice = billdetail.Price * billdetail.Quantity
                        }).ToList();

            return View(list);
        }

        //Cái này là để xem những billdetail nào có trong bill
        //phét








        // GET: BillController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BillController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BillController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BillController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LabNET105/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor contxt;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LabNET105</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LabNET105.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LabNET105</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Sản phẩm</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bill" asp-action="ListBill">Hoá đơn</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn dropdown-toggle text-dark" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    Quản lý sản phẩm
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" asp-action="Create" asp-controller="Product">Thêm mới</a></li>
                                  
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Giỏ hàng</a>
                        </li>

                    </ul>
                </div>
                <div>
                    @if (contxt.HttpContext.Session.GetString("username") != null)
                    {                      
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Xin chào @contxt.HttpContext.Session.GetString("username")
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-action="Logout" asp-controller="Access">Đăng xuất</a></li>
                              
                            </ul>
                        </div>
                    }
                    else
                    {
                        <a asp-action="Index" asp-controller="Access" class="text-black text-decoration-none">Đăng nhập</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LabNET105 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>