LabNET105/Controllers/AccessController.cs
using DAL;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Principal;

namespace LabNET105.Controllers
{
    public class AccessController : Controller
    {
        LabDbContext _context = new LabDbContext();
        private readonly IHttpContextAccessor _contextAccessor;

        public AccessController(IHttpContextAccessor httpContextAccessor)
        {
            _contextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string username, string password)
        {
            var acc = _context.Accounts.FirstOrDefault(x => x.Username == username);
            if (acc == null)
            {
                ViewBag.Error = "Không tồn tại";
                return View();
            }
            else
            {
                if (acc.Password == password)
                {
                    var account = _context.Accounts.FirstOrDefault(x => x.Username == username);
                    _contextAccessor.HttpContext.Session.SetString("username", account.Username);
                    _contextAccessor.HttpContext.Session.SetString("phone", acc.PhoneNumber);
                    _contextAccessor.HttpContext.Session.SetString("uid", acc.Id.ToString());
                    return RedirectToAction("Index", "Home");

                }
                else
                {
                    ViewBag.Error = "Sai TK MK";
                    return View();
                }
            }



        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(string userName, string phone, string pass, string rePass, string addr)
        {
            if (_context.Accounts.FirstOrDefault(x => x.Username == userName) != null || _context.Accounts.FirstOrDefault(x => x.PhoneNumber == phone) != null)
            {
                ViewBag.Error = "Tài khoản đã tồn tại";
            }
            else
            {
                if (pass != rePass)
                {
                    ViewBag.Error = "Mật khẩu không khớp";
                }
                else
                {
                    var acc = new Account();
                    acc.Username = userName;
                    acc.Password = pass;
                    acc.PhoneNumber = phone;
                    acc.Address = addr;
                    _context.Accounts.Add(acc);
                     // khi tạo tài khoản đồng thời Add Giỏ hàng 
                    Cart cart = new Cart()
                    {
                        AccountId = acc.Id,
                        Status =1
                    };
                    _context.Carts.Add(cart);


                    _context.SaveChanges();


                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        public IActionResult Logout()
        {
            _contextAccessor.HttpContext.Session.Remove("username");
            _contextAccessor.HttpContext.Session.Remove("phone");
            _contextAccessor.HttpContext.Session.Remove("uid");
            _contextAccessor.HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
    }
}

LabNET105/Views/Access/Index.cshtml
<div class="d-flex justify-content-center flex-column align-items-center">
    <div class="fw-bold fs-3">Đăng nhập</div>
    <div>
        @if (ViewBag.Error != null)
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.Error
            </div>
        }
        
    </div>
    <div class="w-50">
        <form enctype="multipart/form-data" asp-action="Index">
            <!-- Email input -->
            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="form2Example1">Username</label>
                <input type="text" id="username" name="username" class="form-control" />
            </div>

            <!-- Password input -->
            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="form2Example2">Password</label>
                <input type="password" class="form-control" id="password" name="password" />
            </div>

 

            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Đăng nhập</button>

            <!-- Register buttons -->
            <div class="text-center">
                <p>Không có sao? <a asp-action="Register" asp-controller="Access">Đăng ký ngay</a></p>
                <p>or sign up with:</p>
                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-facebook-f"></i>
                </button>

                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-google"></i>
                </button>

                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-twitter"></i>
                </button>

                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-github"></i>
                </button>
            </div>
        </form>
    </div>
</div>

LabNET105/Views/Access/Register.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="d-flex">
    <div>
        <section class="vh-100">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-lg-12 col-xl-11">
                        <div class="card text-black shadow-sm" style="border-radius: 25px;">
                            <div class="card-body p-md-5">
                                <div class="row justify-content-center">
                                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                        <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Đăng ký</p>

                                        <form class="mx-1 mx-md-4" asp-action="Register">

                                            <div class="d-flex flex-row align-items-center mb-4">
                                                <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                                                    <label class="form-label" for="form3Example1c">Tên tài khoản</label>
                                                    <input type="text" id="userName" name="userName" class="form-control" />
                                                </div>
                                            </div>

                                            <div class="d-flex flex-row align-items-center mb-4">
                                                <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                                                    <label class="form-label" for="form3Example3c">SĐT</label>
                                                    <input type="text" id="phone" name="phone" class="form-control" />
                                                </div>
                                            </div>

                                            <div class="d-flex flex-row align-items-center mb-4">
                                                <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                                                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                                                    <label class="form-label" for="form3Example4cd">Địa chỉ</label>
                                                    <input type="text" id="addr" name="addr" class="form-control" />
                                                </div>
                                            </div>

                                            <div class="d-flex flex-row align-items-center mb-4">
                                                <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                                                    <label class="form-label" for="form3Example4c">Mật khẩu</label>
                                                    <input type="password" id="pass" name="pass" class="form-control" />
                                                </div>
                                            </div>

                                            <div class="d-flex flex-row align-items-center mb-4">
                                                <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                                                <div data-mdb-input-init class="form-outline flex-fill mb-0">
                                                    <label class="form-label" for="form3Example4cd">Nhập lại mật khẩu</label>
                                                    <input type="password" id="rePass" name="rePass" class="form-control" />
                                                </div>
                                            </div>


                                            <div class="form-check d-flex justify-content-center mb-5">
                                                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                                                <label class="form-check-label" for="form2Example3">
                                                    I agree all statements in <a href="#!">Terms of service</a>
                                                </label>
                                            </div>

                                            <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                                <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg">Đăng ký</button>
                                            </div>

                                        </form>

                                    </div>
                                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                             class="img-fluid" alt="Sample image">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

</div>